name: "Tests"
on:
    push:
    schedule:
        - cron: '0 8 * * *'

env:
  ver: 0.1.${{ github.run_number }}

jobs:
    test:
        runs-on: windows-latest

        steps:
        - name: Clone
          uses: actions/checkout@v3

        - name: Test
          run: dotnet test --logger "console;verbosity=detailed"
          
    nuget:
        needs: test
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest

        steps:
        - name: Clone
          uses: actions/checkout@v3

        - name: Create
          run: |
            cd lib
            dotnet pack -c Release /p:Version=$ver
            cd bin/Release
            for file in *.nupkg; do
              new_name="test.nupkg"
              mv "$file" "$new_name"
              break
            done
            dotnet nuget push test.nupkg -k ${{secrets.NUGET_API}} --source https://api.nuget.org/v3/index.json

    docker:
        needs: test
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Build
            run: |
              docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_TOKEN}}
              docker build -t perdub/ddg-ai-proxy:${{env.ver}} -t perdub/ddg-ai-proxy:latest .
              docker image push perdub/ddg-ai-proxy:${{env.ver}}
              docker image push perdub/ddg-ai-proxy:latest

              
    bin-server:
      needs: test
      strategy:
        matrix:
          target-os: ["win-x64", "linux-x64"]
          self-contained: [true, false]
          configuration: ["Debug", "Release"]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: build
          run: |
            dotnet publish web/DdgAiProxy.csproj -c ${{matrix.configuration}} --sc ${{matrix.self-contained}} --os ${{matrix.target-os}} -o /result

        - uses: actions/upload-artifact@v4
          with:
              name: ${{matrix.target-os}}-${{matrix.configuration}}-isSelfContained-${{matrix.self-contained}}
              path: /result



