name: "Nuget Publish"
on:
    push:

jobs:
    nuget:
        runs-on: ubuntu-latest

        steps:
        - name: Clone
          uses: actions/checkout@v3

        - name: Create
          run: |
            cd lib
            dotnet pack -c Release --version-suffix "commit-$GITHUB_SHA"
            cd bin/Release
            for file in *.nupkg; do
              new_name="test.nupkg"
              mv "$file" "$new_name"
              break
            done
            dotnet nuget push test.nupkg -k ${{secrets.NUGET_API}} --source https://api.nuget.org/v3/index.json
