name: "Tests"
on:
    push:
    schedule:
        - cron: '0 8 * * *'

jobs:
    test:
        runs-on: windows-latest

        steps:
        - name: Clone
          uses: actions/checkout@v3

        - name: Test
          run: dotnet test --logger "console;verbosity=detailed"
